#[path = "../../generated/banner_patterns.rs"]
pub(crate) mod banner_patterns;
#[path = "../../generated/biomes.rs"]
pub(crate) mod biomes;
#[path = "../../generated/cat_sound_variants.rs"]
pub(crate) mod cat_sound_variants;
#[path = "../../generated/cat_variants.rs"]
pub(crate) mod cat_variants;
#[path = "../../generated/chicken_sound_variants.rs"]
pub(crate) mod chicken_sound_variants;
#[path = "../../generated/chicken_variants.rs"]
pub(crate) mod chicken_variants;
#[path = "../../generated/cow_sound_variants.rs"]
pub(crate) mod cow_sound_variants;
#[path = "../../generated/cow_variants.rs"]
pub(crate) mod cow_variants;
#[path = "../../generated/damage_types.rs"]
pub(crate) mod damage_types;
#[path = "../../generated/dimension_types.rs"]
pub(crate) mod dimension_types;
#[path = "../../generated/frog_variants.rs"]
pub(crate) mod frog_variants;
#[path = "../../generated/instruments.rs"]
pub(crate) mod instruments;
#[path = "../../generated/jukebox_songs.rs"]
pub(crate) mod jukebox_songs;
#[path = "../../generated/painting_variants.rs"]
pub(crate) mod painting_variants;
#[path = "../../generated/pig_sound_variants.rs"]
pub(crate) mod pig_sound_variants;
#[path = "../../generated/pig_variants.rs"]
pub(crate) mod pig_variants;
#[path = "../../generated/timelines.rs"]
pub(crate) mod timelines;
#[path = "../../generated/trim_materials.rs"]
pub(crate) mod trim_materials;
#[path = "../../generated/wolf_sound_variants.rs"]
pub(crate) mod wolf_sound_variants;
#[path = "../../generated/wolf_variants.rs"]
pub(crate) mod wolf_variants;
#[path = "../../generated/world_clocks.rs"]
pub(crate) mod world_clocks;
#[path = "../../generated/zombie_nautilus_variants.rs"]
pub(crate) mod zombie_nautilus_variants;
