[package]
name = "shulkr"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
description.workspace = true
readme = "../../README.md"


[lib]
doctest = false


[features]
default = ["polar", "anvil", "minimessage"]
anvil = ["dep:bitfield-struct", "dep:flate2", "dep:byteorder"]
polar = ["dep:zstd"]
minimessage = []


[dependencies]
shulkr-nbt = { workspace = true }
shulkr-macros = { workspace = true }
shulkr-data = { workspace = true }

anyhow = { workspace = true }
async-compression = { workspace = true }
bytes = { workspace = true }
rand = { workspace = true }
serde = { workspace = true }
thiserror = { workspace = true }
tokio = { workspace = true }
ureq = { workspace = true }
uuid = { workspace = true }
rustc-hash = { workspace = true }
bitflags = { workspace = true }
indexmap = { workspace = true }
serde_json = { workspace = true }
phf = { workspace = true }
parking_lot = { workspace = true }
hmac = { workspace = true }
sha2 = { workspace = true }
tracing = { workspace = true }
aes = { workspace = true }
cfb8 = { workspace = true }
num-bigint = { workspace = true }
openssl = { workspace = true }
sha1 = { workspace = true }
take_mut = { workspace = true }
futures = { workspace = true }
pastey = { workspace = true }

zstd = { workspace = true, optional = true }
bitfield-struct = { workspace = true, optional = true }
flate2 = { workspace = true, optional = true }
byteorder = { workspace = true, optional = true }

[dev-dependencies]
tracing-subscriber = { workspace = true }

[[example]]
name = "anvil"
required-features = ["anvil"]

[[example]]
name = "polar"
required-features = ["polar"]
