#[derive(Debug, Clone, Copy, PartialEq, Eq, PartialOrd, Ord, Hash)]
pub enum InventoryType {
    Generic9x1,
    Generic9x2,
    Generic9x3,
    Generic9x4,
    Generic9x5,
    Generic9x6,
    Generic3x3,
    Crafter,
    Anvil,
    Beacon,
    BlastFurnace,
    BrewingStand,
    CraftingTable,
    EnchantmentTable,
    Furnace,
    Grindstone,
    Hopper,
    Lectern,
    Loom,
    Merchant,
    ShulkerBox,
    SmithingTable,
    Smoker,
    CartographyTable,
    Stonecutter,
}

impl InventoryType {
    pub fn size(&self) -> i32 {
        match self {
            InventoryType::Generic9x1 => 9,
            InventoryType::Generic9x2 => 18,
            InventoryType::Generic9x3 => 27,
            InventoryType::Generic9x4 => 36,
            InventoryType::Generic9x5 => 45,
            InventoryType::Generic9x6 => 54,
            InventoryType::Generic3x3 => 9,
            InventoryType::Crafter => 9,
            InventoryType::Anvil => 3,
            InventoryType::Beacon => 1,
            InventoryType::BlastFurnace => 3,
            InventoryType::BrewingStand => 5,
            InventoryType::CraftingTable => 10,
            InventoryType::EnchantmentTable => 2,
            InventoryType::Furnace => 3,
            InventoryType::Grindstone => 3,
            InventoryType::Hopper => 5,
            InventoryType::Lectern => 0,
            InventoryType::Loom => 4,
            InventoryType::Merchant => 3,
            InventoryType::ShulkerBox => 27,
            InventoryType::SmithingTable => 4,
            InventoryType::Smoker => 3,
            InventoryType::CartographyTable => 3,
            InventoryType::Stonecutter => 2,
        }
    }

    pub fn id(&self) -> i32 {
        match self {
            InventoryType::Generic9x1 => 0,
            InventoryType::Generic9x2 => 1,
            InventoryType::Generic9x3 => 2,
            InventoryType::Generic9x4 => 3,
            InventoryType::Generic9x5 => 4,
            InventoryType::Generic9x6 => 5,
            InventoryType::Generic3x3 => 6,
            InventoryType::Crafter => 7,
            InventoryType::Anvil => 8,
            InventoryType::Beacon => 9,
            InventoryType::BlastFurnace => 10,
            InventoryType::BrewingStand => 11,
            InventoryType::CraftingTable => 12,
            InventoryType::EnchantmentTable => 13,
            InventoryType::Furnace => 14,
            InventoryType::Grindstone => 15,
            InventoryType::Hopper => 16,
            InventoryType::Lectern => 17,
            InventoryType::Loom => 18,
            InventoryType::Merchant => 19,
            InventoryType::ShulkerBox => 20,
            InventoryType::SmithingTable => 21,
            InventoryType::Smoker => 22,
            InventoryType::CartographyTable => 23,
            InventoryType::Stonecutter => 24,
        }
    }
}
